version: '3.9'
services:
  backend:
    image: node:16-alpine
    container_name: ng_cash_api
    build: ./backend
    ports:
      - 3000:3000
    tty: true
    stdin_open: true    
    restart: always
    working_dir: /app
    command: npm run dev
    volumes: 
      - ./:/app
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:15.1-alpine3.16
    container_name: ng_cash_db
    platform: linux/x86_64
    ports:
      - 5432:5432
    env_file:
      - .env
    restart: 'always'
